AWSTemplateFormatVersion: '2010-09-09'
Description: 'RDS PostgreSQL Database for BGMI Marketplace'

Parameters:
  Environment:
    Type: String
    Default: production
    AllowedValues: [development, staging, production]
  
  DBInstanceClass:
    Type: String
    Default: db.t3.micro
    AllowedValues: [db.t3.micro, db.t3.small, db.t3.medium]
    Description: RDS instance class
  
  DBName:
    Type: String
    Default: bgmi_marketplace
    Description: Database name
  
  DBUsername:
    Type: String
    Default: bgmi_admin
    Description: Database master username
    NoEcho: true

  DBPassword:
    Type: String
    NoEcho: true
    Description: Database master password
    MinLength: 8
    MaxLength: 128

  VpcId:
    Type: AWS::EC2::VPC::Id
    Description: VPC ID for the database

  PrivateSubnet1Id:
    Type: AWS::EC2::Subnet::Id
    Description: Private Subnet 1 ID

  PrivateSubnet2Id:
    Type: AWS::EC2::Subnet::Id
    Description: Private Subnet 2 ID

Resources:
  # DB Subnet Group
  DBSubnetGroup:
    Type: AWS::RDS::DBSubnetGroup
    Properties:
      DBSubnetGroupDescription: Subnet group for BGMI Marketplace database
      SubnetIds:
        - !Ref PrivateSubnet1Id
        - !Ref PrivateSubnet2Id
      Tags:
        - Key: Name
          Value: !Sub '${Environment}-bgmi-marketplace-db-subnet-group'

  # Security Group for RDS
  DatabaseSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupName: !Sub '${Environment}-bgmi-marketplace-db-sg'
      GroupDescription: Security group for RDS database
      VpcId: !Ref VpcId
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 5432
          ToPort: 5432
          SourceSecurityGroupId: !Ref ECSSecurityGroup
      Tags:
        - Key: Name
          Value: !Sub '${Environment}-bgmi-marketplace-db-sg'

  # RDS Parameter Group
  DBParameterGroup:
    Type: AWS::RDS::DBParameterGroup
    Properties:
      DBParameterGroupFamily: postgres15
      Description: Parameter group for BGMI Marketplace PostgreSQL
      Parameters:
        - ParameterName: shared_preload_libraries
          ParameterValue: pg_stat_statements
        - ParameterName: log_statement
          ParameterValue: all
        - ParameterName: log_min_duration_statement
          ParameterValue: '1000'
      Tags:
        - Key: Name
          Value: !Sub '${Environment}-bgmi-marketplace-db-params'

  # RDS Instance
  Database:
    Type: AWS::RDS::DBInstance
    DeletionPolicy: Snapshot
    Properties:
      DBInstanceIdentifier: !Sub '${Environment}-bgmi-marketplace-db'
      DBName: !Ref DBName
      DBInstanceClass: !Ref DBInstanceClass
      Engine: postgres
      EngineVersion: '15.4'
      MasterUsername: !Ref DBUsername
      MasterUserPassword: !Ref DBPassword
      AllocatedStorage: 20
      MaxAllocatedStorage: 100
      StorageType: gp2
      StorageEncrypted: true
      VPCSecurityGroups:
        - !Ref DatabaseSecurityGroup
      DBSubnetGroupName: !Ref DBSubnetGroup
      DBParameterGroupName: !Ref DBParameterGroup
      BackupRetentionPeriod: 7
      PreferredBackupWindow: '03:00-04:00'
      PreferredMaintenanceWindow: 'sun:04:00-sun:05:00'
      MultiAZ: false
      PubliclyAccessible: false
      DeletionProtection: true
      EnableCloudwatchLogsExports:
        - postgresql
      MonitoringInterval: 60
      MonitoringRoleArn: !GetAtt MonitoringRole.Arn
      Tags:
        - Key: Name
          Value: !Sub '${Environment}-bgmi-marketplace-db'

  # CloudWatch Monitoring Role
  MonitoringRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: !Sub '${Environment}-bgmi-marketplace-rds-monitoring-role'
      AssumeRolePolicyDocument:
        Statement:
          - Effect: Allow
            Principal:
              Service: monitoring.rds.amazonaws.com
            Action: sts:AssumeRole
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/service-role/AmazonRDSEnhancedMonitoringRole

  # Secrets Manager Secret for Database Credentials
  DatabaseSecret:
    Type: AWS::SecretsManager::Secret
    Properties:
      Name: !Sub '${Environment}-bgmi-marketplace-db-credentials'
      Description: Database credentials for BGMI Marketplace
      SecretString: !Sub |
        {
          "username": "${DBUsername}",
          "password": "${DBPassword}",
          "engine": "postgres",
          "host": "${Database.Endpoint.Address}",
          "port": 5432,
          "dbname": "${DBName}"
        }
      Tags:
        - Key: Name
          Value: !Sub '${Environment}-bgmi-marketplace-db-secret'

Outputs:
  DatabaseEndpoint:
    Description: RDS instance endpoint
    Value: !GetAtt Database.Endpoint.Address
    Export:
      Name: !Sub '${Environment}-bgmi-marketplace-db-endpoint'

  DatabasePort:
    Description: RDS instance port
    Value: !GetAtt Database.Endpoint.Port
    Export:
      Name: !Sub '${Environment}-bgmi-marketplace-db-port'

  DatabaseName:
    Description: Database name
    Value: !Ref DBName
    Export:
      Name: !Sub '${Environment}-bgmi-marketplace-db-name'

  DatabaseSecretArn:
    Description: ARN of the database secret
    Value: !Ref DatabaseSecret
    Export:
      Name: !Sub '${Environment}-bgmi-marketplace-db-secret-arn'

  DatabaseSecurityGroupId:
    Description: Database security group ID
    Value: !Ref DatabaseSecurityGroup
    Export:
      Name: !Sub '${Environment}-bgmi-marketplace-db-sg-id'
